### ISSUE TITLE
fabric8-setup - Should support WF-Swarm

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-forge#532]
We have support for WF Swarm in f-m-p so the command should be changed to know that
https://github.com/davsclaus/fabric8-hello/blob/master/helloswarm/pom.xml

**Comment by kameshsampath** [comment]
The following steps via forge cli ( after installing the required forge addons)
- project-new --named demo-wildfly
- wildfly-swarm-setup
- fabric8-setup
- devops-pipeline

if you see the generated/updated [pom.xml](https://gist.github.com/kameshsampath/bd4a3a7abc484389fe760a79afdd98fd) it's set to use `fabric8/tomcat-8` image instead of generic java image

https://gist.github.com/kameshsampath/bd4a3a7abc484389fe760a79afdd98fd#file-f8_forge_cli_pom-xml-L41 should be like this 

```
<plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>3.1.38</version>
        <configuration>
          <images>
            <image>
              <name>${project.artifactId}:${project.version}</name>
              <build>
                <from>fabric8/tomcat-8</from>
              </build>
            </image>
          </images>
        </configuration>
      </plugin>
```
